using System;
using System.Collections;
public static partial class GuildBalanceVerification
{
 static void WorkbookParity()
 {
 var game=Create();
 object stats;
 stats=Call(game,"CalculateHeroStats","전사",1); Check(Int(stats,"hp")==42 && Int(stats,"attack")==8 && Int(stats,"defense")==4 && Int(stats,"speed")==3,"Stats 전사1");
 Check((int)Call(game,"HeroExperienceRequired",1)==20, "XP curve");
 stats=Call(game,"CalculateHeroStats","전사",2); Check(Int(stats,"hp")==50 && Int(stats,"attack")==10 && Int(stats,"defense")==4 && Int(stats,"speed")==3,"Stats 전사2");
 Check((int)Call(game,"HeroExperienceRequired",2)==30, "XP curve");
 stats=Call(game,"CalculateHeroStats","전사",3); Check(Int(stats,"hp")==58 && Int(stats,"attack")==12 && Int(stats,"defense")==5 && Int(stats,"speed")==3,"Stats 전사3");
 Check((int)Call(game,"HeroExperienceRequired",3)==44, "XP curve");
 stats=Call(game,"CalculateHeroStats","전사",4); Check(Int(stats,"hp")==66 && Int(stats,"attack")==14 && Int(stats,"defense")==6 && Int(stats,"speed")==3,"Stats 전사4");
 Check((int)Call(game,"HeroExperienceRequired",4)==62, "XP curve");
 stats=Call(game,"CalculateHeroStats","전사",5); Check(Int(stats,"hp")==74 && Int(stats,"attack")==16 && Int(stats,"defense")==7 && Int(stats,"speed")==3,"Stats 전사5");
 Check((int)Call(game,"HeroExperienceRequired",5)==84, "XP curve");
 stats=Call(game,"CalculateHeroStats","전사",6); Check(Int(stats,"hp")==82 && Int(stats,"attack")==18 && Int(stats,"defense")==8 && Int(stats,"speed")==4,"Stats 전사6");
 Check((int)Call(game,"HeroExperienceRequired",6)==110, "XP curve");
 stats=Call(game,"CalculateHeroStats","전사",7); Check(Int(stats,"hp")==90 && Int(stats,"attack")==20 && Int(stats,"defense")==9 && Int(stats,"speed")==4,"Stats 전사7");
 Check((int)Call(game,"HeroExperienceRequired",7)==140, "XP curve");
 stats=Call(game,"CalculateHeroStats","전사",8); Check(Int(stats,"hp")==98 && Int(stats,"attack")==22 && Int(stats,"defense")==10 && Int(stats,"speed")==4,"Stats 전사8");
 Check((int)Call(game,"HeroExperienceRequired",8)==174, "XP curve");
 stats=Call(game,"CalculateHeroStats","전사",9); Check(Int(stats,"hp")==106 && Int(stats,"attack")==24 && Int(stats,"defense")==11 && Int(stats,"speed")==4,"Stats 전사9");
 Check((int)Call(game,"HeroExperienceRequired",9)==212, "XP curve");
 stats=Call(game,"CalculateHeroStats","전사",10); Check(Int(stats,"hp")==114 && Int(stats,"attack")==26 && Int(stats,"defense")==12 && Int(stats,"speed")==4,"Stats 전사10");
 Check((int)Call(game,"HeroExperienceRequired",10)==254, "XP curve");
 stats=Call(game,"CalculateHeroStats","전사",11); Check(Int(stats,"hp")==122 && Int(stats,"attack")==28 && Int(stats,"defense")==13 && Int(stats,"speed")==5,"Stats 전사11");
 Check((int)Call(game,"HeroExperienceRequired",11)==300, "XP curve");
 stats=Call(game,"CalculateHeroStats","전사",12); Check(Int(stats,"hp")==130 && Int(stats,"attack")==30 && Int(stats,"defense")==13 && Int(stats,"speed")==5,"Stats 전사12");
 Check((int)Call(game,"HeroExperienceRequired",12)==350, "XP curve");
 stats=Call(game,"CalculateHeroStats","전사",13); Check(Int(stats,"hp")==138 && Int(stats,"attack")==32 && Int(stats,"defense")==14 && Int(stats,"speed")==5,"Stats 전사13");
 Check((int)Call(game,"HeroExperienceRequired",13)==404, "XP curve");
 stats=Call(game,"CalculateHeroStats","전사",14); Check(Int(stats,"hp")==146 && Int(stats,"attack")==34 && Int(stats,"defense")==15 && Int(stats,"speed")==5,"Stats 전사14");
 Check((int)Call(game,"HeroExperienceRequired",14)==462, "XP curve");
 stats=Call(game,"CalculateHeroStats","전사",15); Check(Int(stats,"hp")==154 && Int(stats,"attack")==36 && Int(stats,"defense")==16 && Int(stats,"speed")==5,"Stats 전사15");
 Check((int)Call(game,"HeroExperienceRequired",15)==524, "XP curve");
 stats=Call(game,"CalculateHeroStats","전사",16); Check(Int(stats,"hp")==162 && Int(stats,"attack")==38 && Int(stats,"defense")==17 && Int(stats,"speed")==6,"Stats 전사16");
 Check((int)Call(game,"HeroExperienceRequired",16)==590, "XP curve");
 stats=Call(game,"CalculateHeroStats","전사",17); Check(Int(stats,"hp")==170 && Int(stats,"attack")==40 && Int(stats,"defense")==18 && Int(stats,"speed")==6,"Stats 전사17");
 Check((int)Call(game,"HeroExperienceRequired",17)==660, "XP curve");
 stats=Call(game,"CalculateHeroStats","전사",18); Check(Int(stats,"hp")==178 && Int(stats,"attack")==42 && Int(stats,"defense")==19 && Int(stats,"speed")==6,"Stats 전사18");
 Check((int)Call(game,"HeroExperienceRequired",18)==734, "XP curve");
 stats=Call(game,"CalculateHeroStats","전사",19); Check(Int(stats,"hp")==186 && Int(stats,"attack")==44 && Int(stats,"defense")==20 && Int(stats,"speed")==6,"Stats 전사19");
 Check((int)Call(game,"HeroExperienceRequired",19)==812, "XP curve");
 stats=Call(game,"CalculateHeroStats","전사",20); Check(Int(stats,"hp")==194 && Int(stats,"attack")==46 && Int(stats,"defense")==21 && Int(stats,"speed")==6,"Stats 전사20");
 Check((int)Call(game,"HeroExperienceRequired",20)==0, "XP curve");
 stats=Call(game,"CalculateHeroStats","마법사",1); Check(Int(stats,"hp")==28 && Int(stats,"attack")==10 && Int(stats,"defense")==1 && Int(stats,"speed")==5,"Stats 마법사1");
 Check((int)Call(game,"HeroExperienceRequired",1)==20, "XP curve");
 stats=Call(game,"CalculateHeroStats","마법사",2); Check(Int(stats,"hp")==34 && Int(stats,"attack")==12 && Int(stats,"defense")==1 && Int(stats,"speed")==5,"Stats 마법사2");
 Check((int)Call(game,"HeroExperienceRequired",2)==30, "XP curve");
 stats=Call(game,"CalculateHeroStats","마법사",3); Check(Int(stats,"hp")==39 && Int(stats,"attack")==14 && Int(stats,"defense")==1 && Int(stats,"speed")==5,"Stats 마법사3");
 Check((int)Call(game,"HeroExperienceRequired",3)==44, "XP curve");
 stats=Call(game,"CalculateHeroStats","마법사",4); Check(Int(stats,"hp")==45 && Int(stats,"attack")==16 && Int(stats,"defense")==1 && Int(stats,"speed")==5,"Stats 마법사4");
 Check((int)Call(game,"HeroExperienceRequired",4)==62, "XP curve");
 stats=Call(game,"CalculateHeroStats","마법사",5); Check(Int(stats,"hp")==50 && Int(stats,"attack")==18 && Int(stats,"defense")==2 && Int(stats,"speed")==6,"Stats 마법사5");
 Check((int)Call(game,"HeroExperienceRequired",5)==84, "XP curve");
 stats=Call(game,"CalculateHeroStats","마법사",6); Check(Int(stats,"hp")==56 && Int(stats,"attack")==20 && Int(stats,"defense")==2 && Int(stats,"speed")==6,"Stats 마법사6");
 Check((int)Call(game,"HeroExperienceRequired",6)==110, "XP curve");
 stats=Call(game,"CalculateHeroStats","마법사",7); Check(Int(stats,"hp")==61 && Int(stats,"attack")==22 && Int(stats,"defense")==2 && Int(stats,"speed")==6,"Stats 마법사7");
 Check((int)Call(game,"HeroExperienceRequired",7)==140, "XP curve");
 stats=Call(game,"CalculateHeroStats","마법사",8); Check(Int(stats,"hp")==67 && Int(stats,"attack")==24 && Int(stats,"defense")==2 && Int(stats,"speed")==6,"Stats 마법사8");
 Check((int)Call(game,"HeroExperienceRequired",8)==174, "XP curve");
 stats=Call(game,"CalculateHeroStats","마법사",9); Check(Int(stats,"hp")==72 && Int(stats,"attack")==26 && Int(stats,"defense")==3 && Int(stats,"speed")==7,"Stats 마법사9");
 Check((int)Call(game,"HeroExperienceRequired",9)==212, "XP curve");
 stats=Call(game,"CalculateHeroStats","마법사",10); Check(Int(stats,"hp")==78 && Int(stats,"attack")==28 && Int(stats,"defense")==3 && Int(stats,"speed")==7,"Stats 마법사10");
 Check((int)Call(game,"HeroExperienceRequired",10)==254, "XP curve");
 stats=Call(game,"CalculateHeroStats","마법사",11); Check(Int(stats,"hp")==83 && Int(stats,"attack")==30 && Int(stats,"defense")==3 && Int(stats,"speed")==7,"Stats 마법사11");
 Check((int)Call(game,"HeroExperienceRequired",11)==300, "XP curve");
 stats=Call(game,"CalculateHeroStats","마법사",12); Check(Int(stats,"hp")==89 && Int(stats,"attack")==32 && Int(stats,"defense")==3 && Int(stats,"speed")==7,"Stats 마법사12");
 Check((int)Call(game,"HeroExperienceRequired",12)==350, "XP curve");
 stats=Call(game,"CalculateHeroStats","마법사",13); Check(Int(stats,"hp")==94 && Int(stats,"attack")==34 && Int(stats,"defense")==4 && Int(stats,"speed")==8,"Stats 마법사13");
 Check((int)Call(game,"HeroExperienceRequired",13)==404, "XP curve");
 stats=Call(game,"CalculateHeroStats","마법사",14); Check(Int(stats,"hp")==100 && Int(stats,"attack")==36 && Int(stats,"defense")==4 && Int(stats,"speed")==8,"Stats 마법사14");
 Check((int)Call(game,"HeroExperienceRequired",14)==462, "XP curve");
 stats=Call(game,"CalculateHeroStats","마법사",15); Check(Int(stats,"hp")==105 && Int(stats,"attack")==38 && Int(stats,"defense")==4 && Int(stats,"speed")==8,"Stats 마법사15");
 Check((int)Call(game,"HeroExperienceRequired",15)==524, "XP curve");
 stats=Call(game,"CalculateHeroStats","마법사",16); Check(Int(stats,"hp")==111 && Int(stats,"attack")==40 && Int(stats,"defense")==4 && Int(stats,"speed")==8,"Stats 마법사16");
 Check((int)Call(game,"HeroExperienceRequired",16)==590, "XP curve");
 stats=Call(game,"CalculateHeroStats","마법사",17); Check(Int(stats,"hp")==116 && Int(stats,"attack")==42 && Int(stats,"defense")==5 && Int(stats,"speed")==9,"Stats 마법사17");
 Check((int)Call(game,"HeroExperienceRequired",17)==660, "XP curve");
 stats=Call(game,"CalculateHeroStats","마법사",18); Check(Int(stats,"hp")==122 && Int(stats,"attack")==44 && Int(stats,"defense")==5 && Int(stats,"speed")==9,"Stats 마법사18");
 Check((int)Call(game,"HeroExperienceRequired",18)==734, "XP curve");
 stats=Call(game,"CalculateHeroStats","마법사",19); Check(Int(stats,"hp")==127 && Int(stats,"attack")==46 && Int(stats,"defense")==5 && Int(stats,"speed")==9,"Stats 마법사19");
 Check((int)Call(game,"HeroExperienceRequired",19)==812, "XP curve");
 stats=Call(game,"CalculateHeroStats","마법사",20); Check(Int(stats,"hp")==133 && Int(stats,"attack")==48 && Int(stats,"defense")==5 && Int(stats,"speed")==9,"Stats 마법사20");
 Check((int)Call(game,"HeroExperienceRequired",20)==0, "XP curve");
 stats=Call(game,"CalculateHeroStats","궁수",1); Check(Int(stats,"hp")==32 && Int(stats,"attack")==9 && Int(stats,"defense")==2 && Int(stats,"speed")==7,"Stats 궁수1");
 Check((int)Call(game,"HeroExperienceRequired",1)==20, "XP curve");
 stats=Call(game,"CalculateHeroStats","궁수",2); Check(Int(stats,"hp")==38 && Int(stats,"attack")==11 && Int(stats,"defense")==2 && Int(stats,"speed")==7,"Stats 궁수2");
 Check((int)Call(game,"HeroExperienceRequired",2)==30, "XP curve");
 stats=Call(game,"CalculateHeroStats","궁수",3); Check(Int(stats,"hp")==44 && Int(stats,"attack")==13 && Int(stats,"defense")==2 && Int(stats,"speed")==7,"Stats 궁수3");
 Check((int)Call(game,"HeroExperienceRequired",3)==44, "XP curve");
 stats=Call(game,"CalculateHeroStats","궁수",4); Check(Int(stats,"hp")==50 && Int(stats,"attack")==15 && Int(stats,"defense")==2 && Int(stats,"speed")==8,"Stats 궁수4");
 Check((int)Call(game,"HeroExperienceRequired",4)==62, "XP curve");
 stats=Call(game,"CalculateHeroStats","궁수",5); Check(Int(stats,"hp")==56 && Int(stats,"attack")==17 && Int(stats,"defense")==2 && Int(stats,"speed")==8,"Stats 궁수5");
 Check((int)Call(game,"HeroExperienceRequired",5)==84, "XP curve");
 stats=Call(game,"CalculateHeroStats","궁수",6); Check(Int(stats,"hp")==62 && Int(stats,"attack")==19 && Int(stats,"defense")==3 && Int(stats,"speed")==8,"Stats 궁수6");
 Check((int)Call(game,"HeroExperienceRequired",6)==110, "XP curve");
 stats=Call(game,"CalculateHeroStats","궁수",7); Check(Int(stats,"hp")==68 && Int(stats,"attack")==21 && Int(stats,"defense")==3 && Int(stats,"speed")==9,"Stats 궁수7");
 Check((int)Call(game,"HeroExperienceRequired",7)==140, "XP curve");
 stats=Call(game,"CalculateHeroStats","궁수",8); Check(Int(stats,"hp")==74 && Int(stats,"attack")==23 && Int(stats,"defense")==3 && Int(stats,"speed")==9,"Stats 궁수8");
 Check((int)Call(game,"HeroExperienceRequired",8)==174, "XP curve");
 stats=Call(game,"CalculateHeroStats","궁수",9); Check(Int(stats,"hp")==80 && Int(stats,"attack")==25 && Int(stats,"defense")==3 && Int(stats,"speed")==9,"Stats 궁수9");
 Check((int)Call(game,"HeroExperienceRequired",9)==212, "XP curve");
 stats=Call(game,"CalculateHeroStats","궁수",10); Check(Int(stats,"hp")==86 && Int(stats,"attack")==27 && Int(stats,"defense")==3 && Int(stats,"speed")==10,"Stats 궁수10");
 Check((int)Call(game,"HeroExperienceRequired",10)==254, "XP curve");
 stats=Call(game,"CalculateHeroStats","궁수",11); Check(Int(stats,"hp")==92 && Int(stats,"attack")==29 && Int(stats,"defense")==4 && Int(stats,"speed")==10,"Stats 궁수11");
 Check((int)Call(game,"HeroExperienceRequired",11)==300, "XP curve");
 stats=Call(game,"CalculateHeroStats","궁수",12); Check(Int(stats,"hp")==98 && Int(stats,"attack")==31 && Int(stats,"defense")==4 && Int(stats,"speed")==10,"Stats 궁수12");
 Check((int)Call(game,"HeroExperienceRequired",12)==350, "XP curve");
 stats=Call(game,"CalculateHeroStats","궁수",13); Check(Int(stats,"hp")==104 && Int(stats,"attack")==33 && Int(stats,"defense")==4 && Int(stats,"speed")==11,"Stats 궁수13");
 Check((int)Call(game,"HeroExperienceRequired",13)==404, "XP curve");
 stats=Call(game,"CalculateHeroStats","궁수",14); Check(Int(stats,"hp")==110 && Int(stats,"attack")==35 && Int(stats,"defense")==4 && Int(stats,"speed")==11,"Stats 궁수14");
 Check((int)Call(game,"HeroExperienceRequired",14)==462, "XP curve");
 stats=Call(game,"CalculateHeroStats","궁수",15); Check(Int(stats,"hp")==116 && Int(stats,"attack")==37 && Int(stats,"defense")==4 && Int(stats,"speed")==11,"Stats 궁수15");
 Check((int)Call(game,"HeroExperienceRequired",15)==524, "XP curve");
 stats=Call(game,"CalculateHeroStats","궁수",16); Check(Int(stats,"hp")==122 && Int(stats,"attack")==39 && Int(stats,"defense")==5 && Int(stats,"speed")==12,"Stats 궁수16");
 Check((int)Call(game,"HeroExperienceRequired",16)==590, "XP curve");
 stats=Call(game,"CalculateHeroStats","궁수",17); Check(Int(stats,"hp")==128 && Int(stats,"attack")==41 && Int(stats,"defense")==5 && Int(stats,"speed")==12,"Stats 궁수17");
 Check((int)Call(game,"HeroExperienceRequired",17)==660, "XP curve");
 stats=Call(game,"CalculateHeroStats","궁수",18); Check(Int(stats,"hp")==134 && Int(stats,"attack")==43 && Int(stats,"defense")==5 && Int(stats,"speed")==12,"Stats 궁수18");
 Check((int)Call(game,"HeroExperienceRequired",18)==734, "XP curve");
 stats=Call(game,"CalculateHeroStats","궁수",19); Check(Int(stats,"hp")==140 && Int(stats,"attack")==45 && Int(stats,"defense")==5 && Int(stats,"speed")==13,"Stats 궁수19");
 Check((int)Call(game,"HeroExperienceRequired",19)==812, "XP curve");
 stats=Call(game,"CalculateHeroStats","궁수",20); Check(Int(stats,"hp")==146 && Int(stats,"attack")==47 && Int(stats,"defense")==5 && Int(stats,"speed")==13,"Stats 궁수20");
 Check((int)Call(game,"HeroExperienceRequired",20)==0, "XP curve");
 stats=Call(game,"CalculateHeroStats","도적",1); Check(Int(stats,"hp")==34 && Int(stats,"attack")==9 && Int(stats,"defense")==2 && Int(stats,"speed")==7,"Stats 도적1");
 Check((int)Call(game,"HeroExperienceRequired",1)==20, "XP curve");
 stats=Call(game,"CalculateHeroStats","도적",2); Check(Int(stats,"hp")==40 && Int(stats,"attack")==11 && Int(stats,"defense")==2 && Int(stats,"speed")==7,"Stats 도적2");
 Check((int)Call(game,"HeroExperienceRequired",2)==30, "XP curve");
 stats=Call(game,"CalculateHeroStats","도적",3); Check(Int(stats,"hp")==46 && Int(stats,"attack")==13 && Int(stats,"defense")==3 && Int(stats,"speed")==7,"Stats 도적3");
 Check((int)Call(game,"HeroExperienceRequired",3)==44, "XP curve");
 stats=Call(game,"CalculateHeroStats","도적",4); Check(Int(stats,"hp")==52 && Int(stats,"attack")==15 && Int(stats,"defense")==3 && Int(stats,"speed")==8,"Stats 도적4");
 Check((int)Call(game,"HeroExperienceRequired",4)==62, "XP curve");
 stats=Call(game,"CalculateHeroStats","도적",5); Check(Int(stats,"hp")==58 && Int(stats,"attack")==17 && Int(stats,"defense")==4 && Int(stats,"speed")==8,"Stats 도적5");
 Check((int)Call(game,"HeroExperienceRequired",5)==84, "XP curve");
 stats=Call(game,"CalculateHeroStats","도적",6); Check(Int(stats,"hp")==64 && Int(stats,"attack")==19 && Int(stats,"defense")==5 && Int(stats,"speed")==8,"Stats 도적6");
 Check((int)Call(game,"HeroExperienceRequired",6)==110, "XP curve");
 stats=Call(game,"CalculateHeroStats","도적",7); Check(Int(stats,"hp")==70 && Int(stats,"attack")==21 && Int(stats,"defense")==5 && Int(stats,"speed")==9,"Stats 도적7");
 Check((int)Call(game,"HeroExperienceRequired",7)==140, "XP curve");
 stats=Call(game,"CalculateHeroStats","도적",8); Check(Int(stats,"hp")==76 && Int(stats,"attack")==23 && Int(stats,"defense")==6 && Int(stats,"speed")==9,"Stats 도적8");
 Check((int)Call(game,"HeroExperienceRequired",8)==174, "XP curve");
 stats=Call(game,"CalculateHeroStats","도적",9); Check(Int(stats,"hp")==82 && Int(stats,"attack")==25 && Int(stats,"defense")==6 && Int(stats,"speed")==9,"Stats 도적9");
 Check((int)Call(game,"HeroExperienceRequired",9)==212, "XP curve");
 stats=Call(game,"CalculateHeroStats","도적",10); Check(Int(stats,"hp")==88 && Int(stats,"attack")==27 && Int(stats,"defense")==7 && Int(stats,"speed")==10,"Stats 도적10");
 Check((int)Call(game,"HeroExperienceRequired",10)==254, "XP curve");
 stats=Call(game,"CalculateHeroStats","도적",11); Check(Int(stats,"hp")==94 && Int(stats,"attack")==29 && Int(stats,"defense")==8 && Int(stats,"speed")==10,"Stats 도적11");
 Check((int)Call(game,"HeroExperienceRequired",11)==300, "XP curve");
 stats=Call(game,"CalculateHeroStats","도적",12); Check(Int(stats,"hp")==100 && Int(stats,"attack")==31 && Int(stats,"defense")==8 && Int(stats,"speed")==10,"Stats 도적12");
 Check((int)Call(game,"HeroExperienceRequired",12)==350, "XP curve");
 stats=Call(game,"CalculateHeroStats","도적",13); Check(Int(stats,"hp")==106 && Int(stats,"attack")==33 && Int(stats,"defense")==9 && Int(stats,"speed")==11,"Stats 도적13");
 Check((int)Call(game,"HeroExperienceRequired",13)==404, "XP curve");
 stats=Call(game,"CalculateHeroStats","도적",14); Check(Int(stats,"hp")==112 && Int(stats,"attack")==35 && Int(stats,"defense")==9 && Int(stats,"speed")==11,"Stats 도적14");
 Check((int)Call(game,"HeroExperienceRequired",14)==462, "XP curve");
 stats=Call(game,"CalculateHeroStats","도적",15); Check(Int(stats,"hp")==118 && Int(stats,"attack")==37 && Int(stats,"defense")==10 && Int(stats,"speed")==11,"Stats 도적15");
 Check((int)Call(game,"HeroExperienceRequired",15)==524, "XP curve");
 stats=Call(game,"CalculateHeroStats","도적",16); Check(Int(stats,"hp")==124 && Int(stats,"attack")==39 && Int(stats,"defense")==11 && Int(stats,"speed")==12,"Stats 도적16");
 Check((int)Call(game,"HeroExperienceRequired",16)==590, "XP curve");
 stats=Call(game,"CalculateHeroStats","도적",17); Check(Int(stats,"hp")==130 && Int(stats,"attack")==41 && Int(stats,"defense")==11 && Int(stats,"speed")==12,"Stats 도적17");
 Check((int)Call(game,"HeroExperienceRequired",17)==660, "XP curve");
 stats=Call(game,"CalculateHeroStats","도적",18); Check(Int(stats,"hp")==136 && Int(stats,"attack")==43 && Int(stats,"defense")==12 && Int(stats,"speed")==12,"Stats 도적18");
 Check((int)Call(game,"HeroExperienceRequired",18)==734, "XP curve");
 stats=Call(game,"CalculateHeroStats","도적",19); Check(Int(stats,"hp")==142 && Int(stats,"attack")==45 && Int(stats,"defense")==12 && Int(stats,"speed")==13,"Stats 도적19");
 Check((int)Call(game,"HeroExperienceRequired",19)==812, "XP curve");
 stats=Call(game,"CalculateHeroStats","도적",20); Check(Int(stats,"hp")==148 && Int(stats,"attack")==47 && Int(stats,"defense")==13 && Int(stats,"speed")==13,"Stats 도적20");
 Check((int)Call(game,"HeroExperienceRequired",20)==0, "XP curve");
 Array[] items=(Array[])Get(game,"inventory"); int[][] recipes=(int[][])Get(game,"recipes");
 object item; int offset,index;
 index=-1; for(int i=0;i<items[0].Length;i++) if((string)Get(items[0].GetValue(i),"name")=="곡물 빵") index=i;
 Check(index>=0,"곡물 빵 missing"); item=items[0].GetValue(index);
 Check(Int(item,"price")==8 && Int(item,"unlockGuildLevel")==1 && Int(item,"productionCost")==0 && Int(item,"hpRecovery")==8 && Int(item,"attackBonus")==0 && Int(item,"defenseBonus")==0 && (string)Get(item,"allowedJob")=="전 직업","곡물 빵 values");
 offset=index; for(int c=0;c<0;c++) offset+=items[c].Length;
 Check(string.Join(",",recipes[offset])=="2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0","곡물 빵 recipe");
 index=-1; for(int i=0;i<items[0].Length;i++) if((string)Get(items[0].GetValue(i),"name")=="산딸기 수프") index=i;
 Check(index>=0,"산딸기 수프 missing"); item=items[0].GetValue(index);
 Check(Int(item,"price")==10 && Int(item,"unlockGuildLevel")==2 && Int(item,"productionCost")==0 && Int(item,"hpRecovery")==12 && Int(item,"attackBonus")==0 && Int(item,"defenseBonus")==0 && (string)Get(item,"allowedJob")=="전 직업","산딸기 수프 values");
 offset=index; for(int c=0;c<0;c++) offset+=items[c].Length;
 Check(string.Join(",",recipes[offset])=="0,2,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0","산딸기 수프 recipe");
 index=-1; for(int i=0;i<items[0].Length;i++) if((string)Get(items[0].GetValue(i),"name")=="구운 고기") index=i;
 Check(index>=0,"구운 고기 missing"); item=items[0].GetValue(index);
 Check(Int(item,"price")==14 && Int(item,"unlockGuildLevel")==1 && Int(item,"productionCost")==0 && Int(item,"hpRecovery")==16 && Int(item,"attackBonus")==0 && Int(item,"defenseBonus")==0 && (string)Get(item,"allowedJob")=="전 직업","구운 고기 values");
 offset=index; for(int c=0;c<0;c++) offset+=items[c].Length;
 Check(string.Join(",",recipes[offset])=="0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0","구운 고기 recipe");
 index=-1; for(int i=0;i<items[0].Length;i++) if((string)Get(items[0].GetValue(i),"name")=="허브 고기구이") index=i;
 Check(index>=0,"허브 고기구이 missing"); item=items[0].GetValue(index);
 Check(Int(item,"price")==24 && Int(item,"unlockGuildLevel")==3 && Int(item,"productionCost")==1 && Int(item,"hpRecovery")==24 && Int(item,"attackBonus")==0 && Int(item,"defenseBonus")==0 && (string)Get(item,"allowedJob")=="전 직업","허브 고기구이 values");
 offset=index; for(int c=0;c<0;c++) offset+=items[c].Length;
 Check(string.Join(",",recipes[offset])=="0,0,2,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0","허브 고기구이 recipe");
 index=-1; for(int i=0;i<items[0].Length;i++) if((string)Get(items[0].GetValue(i),"name")=="버섯 파이") index=i;
 Check(index>=0,"버섯 파이 missing"); item=items[0].GetValue(index);
 Check(Int(item,"price")==28 && Int(item,"unlockGuildLevel")==4 && Int(item,"productionCost")==1 && Int(item,"hpRecovery")==28 && Int(item,"attackBonus")==0 && Int(item,"defenseBonus")==0 && (string)Get(item,"allowedJob")=="전 직업","버섯 파이 values");
 offset=index; for(int c=0;c<0;c++) offset+=items[c].Length;
 Check(string.Join(",",recipes[offset])=="2,0,0,0,0,0,0,2,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0","버섯 파이 recipe");
 index=-1; for(int i=0;i<items[0].Length;i++) if((string)Get(items[0].GetValue(i),"name")=="사과 훈제구이") index=i;
 Check(index>=0,"사과 훈제구이 missing"); item=items[0].GetValue(index);
 Check(Int(item,"price")==32 && Int(item,"unlockGuildLevel")==4 && Int(item,"productionCost")==1 && Int(item,"hpRecovery")==32 && Int(item,"attackBonus")==0 && Int(item,"defenseBonus")==0 && (string)Get(item,"allowedJob")=="전 직업","사과 훈제구이 values");
 offset=index; for(int c=0;c<0;c++) offset+=items[c].Length;
 Check(string.Join(",",recipes[offset])=="0,0,2,0,0,0,0,0,0,0,0,2,0,0,1,0,0,0,0,0,0,0,0,0","사과 훈제구이 recipe");
 index=-1; for(int i=0;i<items[0].Length;i++) if((string)Get(items[0].GetValue(i),"name")=="왕실 만찬") index=i;
 Check(index>=0,"왕실 만찬 missing"); item=items[0].GetValue(index);
 Check(Int(item,"price")==65 && Int(item,"unlockGuildLevel")==8 && Int(item,"productionCost")==2 && Int(item,"hpRecovery")==40 && Int(item,"attackBonus")==0 && Int(item,"defenseBonus")==0 && (string)Get(item,"allowedJob")=="전 직업","왕실 만찬 values");
 offset=index; for(int c=0;c<0;c++) offset+=items[c].Length;
 Check(string.Join(",",recipes[offset])=="0,0,3,0,0,0,0,2,0,0,0,0,2,0,0,0,0,0,0,0,0,1,0,0","왕실 만찬 recipe");
 index=-1; for(int i=0;i<items[0].Length;i++) if((string)Get(items[0].GetValue(i),"name")=="달빛 산딸기 타르트") index=i;
 Check(index>=0,"달빛 산딸기 타르트 missing"); item=items[0].GetValue(index);
 Check(Int(item,"price")==62 && Int(item,"unlockGuildLevel")==9 && Int(item,"productionCost")==2 && Int(item,"hpRecovery")==48 && Int(item,"attackBonus")==0 && Int(item,"defenseBonus")==0 && (string)Get(item,"allowedJob")=="전 직업","달빛 산딸기 타르트 values");
 offset=index; for(int c=0;c<0;c++) offset+=items[c].Length;
 Check(string.Join(",",recipes[offset])=="2,3,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1","달빛 산딸기 타르트 recipe");
 index=-1; for(int i=0;i<items[0].Length;i++) if((string)Get(items[0].GetValue(i),"name")=="영웅 스테이크") index=i;
 Check(index>=0,"영웅 스테이크 missing"); item=items[0].GetValue(index);
 Check(Int(item,"price")==80 && Int(item,"unlockGuildLevel")==9 && Int(item,"productionCost")==2 && Int(item,"hpRecovery")==60 && Int(item,"attackBonus")==0 && Int(item,"defenseBonus")==0 && (string)Get(item,"allowedJob")=="전 직업","영웅 스테이크 values");
 offset=index; for(int c=0;c<0;c++) offset+=items[c].Length;
 Check(string.Join(",",recipes[offset])=="0,0,4,0,0,0,2,0,0,0,0,0,2,0,0,0,0,0,1,0,0,0,0,0","영웅 스테이크 recipe");
 index=-1; for(int i=0;i<items[1].Length;i++) if((string)Get(items[1].GetValue(i),"name")=="견습자의 검") index=i;
 Check(index>=0,"견습자의 검 missing"); item=items[1].GetValue(index);
 Check(Int(item,"price")==20 && Int(item,"unlockGuildLevel")==1 && Int(item,"productionCost")==0 && Int(item,"hpRecovery")==0 && Int(item,"attackBonus")==3 && Int(item,"defenseBonus")==0 && (string)Get(item,"allowedJob")=="전사","견습자의 검 values");
 offset=index; for(int c=0;c<1;c++) offset+=items[c].Length;
 Check(string.Join(",",recipes[offset])=="0,0,0,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0","견습자의 검 recipe");
 index=-1; for(int i=0;i<items[1].Length;i++) if((string)Get(items[1].GetValue(i),"name")=="사냥꾼의 활") index=i;
 Check(index>=0,"사냥꾼의 활 missing"); item=items[1].GetValue(index);
 Check(Int(item,"price")==28 && Int(item,"unlockGuildLevel")==1 && Int(item,"productionCost")==0 && Int(item,"hpRecovery")==0 && Int(item,"attackBonus")==3 && Int(item,"defenseBonus")==0 && (string)Get(item,"allowedJob")=="궁수","사냥꾼의 활 values");
 offset=index; for(int c=0;c<1;c++) offset+=items[c].Length;
 Check(string.Join(",",recipes[offset])=="0,0,0,2,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0","사냥꾼의 활 recipe");
 index=-1; for(int i=0;i<items[1].Length;i++) if((string)Get(items[1].GetValue(i),"name")=="참나무 지팡이") index=i;
 Check(index>=0,"참나무 지팡이 missing"); item=items[1].GetValue(index);
 Check(Int(item,"price")==24 && Int(item,"unlockGuildLevel")==1 && Int(item,"productionCost")==0 && Int(item,"hpRecovery")==0 && Int(item,"attackBonus")==3 && Int(item,"defenseBonus")==0 && (string)Get(item,"allowedJob")=="마법사","참나무 지팡이 values");
 offset=index; for(int c=0;c<1;c++) offset+=items[c].Length;
 Check(string.Join(",",recipes[offset])=="0,1,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0","참나무 지팡이 recipe");
 index=-1; for(int i=0;i<items[1].Length;i++) if((string)Get(items[1].GetValue(i),"name")=="강철 장검") index=i;
 Check(index>=0,"강철 장검 missing"); item=items[1].GetValue(index);
 Check(Int(item,"price")==55 && Int(item,"unlockGuildLevel")==3 && Int(item,"productionCost")==1 && Int(item,"hpRecovery")==0 && Int(item,"attackBonus")==7 && Int(item,"defenseBonus")==0 && (string)Get(item,"allowedJob")=="전사","강철 장검 values");
 offset=index; for(int c=0;c<1;c++) offset+=items[c].Length;
 Check(string.Join(",",recipes[offset])=="0,0,0,1,4,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0","강철 장검 recipe");
 index=-1; for(int i=0;i<items[1].Length;i++) if((string)Get(items[1].GetValue(i),"name")=="장인의 장궁") index=i;
 Check(index>=0,"장인의 장궁 missing"); item=items[1].GetValue(index);
 Check(Int(item,"price")==68 && Int(item,"unlockGuildLevel")==4 && Int(item,"productionCost")==1 && Int(item,"hpRecovery")==0 && Int(item,"attackBonus")==7 && Int(item,"defenseBonus")==0 && (string)Get(item,"allowedJob")=="궁수","장인의 장궁 values");
 offset=index; for(int c=0;c<1;c++) offset+=items[c].Length;
 Check(string.Join(",",recipes[offset])=="0,0,0,4,0,2,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0","장인의 장궁 recipe");
 index=-1; for(int i=0;i<items[1].Length;i++) if((string)Get(items[1].GetValue(i),"name")=="마도사의 지팡이") index=i;
 Check(index>=0,"마도사의 지팡이 missing"); item=items[1].GetValue(index);
 Check(Int(item,"price")==62 && Int(item,"unlockGuildLevel")==7 && Int(item,"productionCost")==1 && Int(item,"hpRecovery")==0 && Int(item,"attackBonus")==8 && Int(item,"defenseBonus")==0 && (string)Get(item,"allowedJob")=="마법사","마도사의 지팡이 values");
 offset=index; for(int c=0;c<1;c++) offset+=items[c].Length;
 Check(string.Join(",",recipes[offset])=="0,0,0,2,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0","마도사의 지팡이 recipe");
 index=-1; for(int i=0;i<items[1].Length;i++) if((string)Get(items[1].GetValue(i),"name")=="왕가의 검") index=i;
 Check(index>=0,"왕가의 검 missing"); item=items[1].GetValue(index);
 Check(Int(item,"price")==120 && Int(item,"unlockGuildLevel")==8 && Int(item,"productionCost")==2 && Int(item,"hpRecovery")==0 && Int(item,"attackBonus")==13 && Int(item,"defenseBonus")==0 && (string)Get(item,"allowedJob")=="전사","왕가의 검 values");
 offset=index; for(int c=0;c<1;c++) offset+=items[c].Length;
 Check(string.Join(",",recipes[offset])=="0,0,0,0,4,0,0,0,0,0,0,0,0,0,2,2,0,0,1,0,0,0,0,0","왕가의 검 recipe");
 index=-1; for(int i=0;i<items[1].Length;i++) if((string)Get(items[1].GetValue(i),"name")=="용사냥 장궁") index=i;
 Check(index>=0,"용사냥 장궁 missing"); item=items[1].GetValue(index);
 Check(Int(item,"price")==145 && Int(item,"unlockGuildLevel")==8 && Int(item,"productionCost")==2 && Int(item,"hpRecovery")==0 && Int(item,"attackBonus")==13 && Int(item,"defenseBonus")==0 && (string)Get(item,"allowedJob")=="궁수","용사냥 장궁 values");
 offset=index; for(int c=0;c<1;c++) offset+=items[c].Length;
 Check(string.Join(",",recipes[offset])=="0,0,0,4,0,3,0,0,0,2,0,0,0,0,0,2,0,0,0,0,1,0,0,0","용사냥 장궁 recipe");
 index=-1; for(int i=0;i<items[1].Length;i++) if((string)Get(items[1].GetValue(i),"name")=="대마법사의 지팡이") index=i;
 Check(index>=0,"대마법사의 지팡이 missing"); item=items[1].GetValue(index);
 Check(Int(item,"price")==135 && Int(item,"unlockGuildLevel")==9 && Int(item,"productionCost")==2 && Int(item,"hpRecovery")==0 && Int(item,"attackBonus")==15 && Int(item,"defenseBonus")==0 && (string)Get(item,"allowedJob")=="마법사","대마법사의 지팡이 values");
 offset=index; for(int c=0;c<1;c++) offset+=items[c].Length;
 Check(string.Join(",",recipes[offset])=="0,0,0,3,0,0,0,0,2,0,0,0,0,0,0,1,2,0,0,1,0,0,0,0","대마법사의 지팡이 recipe");
 index=-1; for(int i=0;i<items[2].Length;i++) if((string)Get(items[2].GetValue(i),"name")=="가죽 조끼") index=i;
 Check(index>=0,"가죽 조끼 missing"); item=items[2].GetValue(index);
 Check(Int(item,"price")==18 && Int(item,"unlockGuildLevel")==1 && Int(item,"productionCost")==0 && Int(item,"hpRecovery")==0 && Int(item,"attackBonus")==0 && Int(item,"defenseBonus")==2 && (string)Get(item,"allowedJob")=="전사·궁수","가죽 조끼 values");
 offset=index; for(int c=0;c<2;c++) offset+=items[c].Length;
 Check(string.Join(",",recipes[offset])=="0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0","가죽 조끼 recipe");
 index=-1; for(int i=0;i<items[2].Length;i++) if((string)Get(items[2].GetValue(i),"name")=="작은 방패") index=i;
 Check(index>=0,"작은 방패 missing"); item=items[2].GetValue(index);
 Check(Int(item,"price")==22 && Int(item,"unlockGuildLevel")==1 && Int(item,"productionCost")==0 && Int(item,"hpRecovery")==0 && Int(item,"attackBonus")==0 && Int(item,"defenseBonus")==3 && (string)Get(item,"allowedJob")=="전사","작은 방패 values");
 offset=index; for(int c=0;c<2;c++) offset+=items[c].Length;
 Check(string.Join(",",recipes[offset])=="0,0,0,2,1,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0","작은 방패 recipe");
 index=-1; for(int i=0;i<items[2].Length;i++) if((string)Get(items[2].GetValue(i),"name")=="여행자 망토") index=i;
 Check(index>=0,"여행자 망토 missing"); item=items[2].GetValue(index);
 Check(Int(item,"price")==16 && Int(item,"unlockGuildLevel")==1 && Int(item,"productionCost")==0 && Int(item,"hpRecovery")==0 && Int(item,"attackBonus")==0 && Int(item,"defenseBonus")==1 && (string)Get(item,"allowedJob")=="전 직업","여행자 망토 values");
 offset=index; for(int c=0;c<2;c++) offset+=items[c].Length;
 Check(string.Join(",",recipes[offset])=="0,1,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0","여행자 망토 recipe");
 index=-1; for(int i=0;i<items[2].Length;i++) if((string)Get(items[2].GetValue(i),"name")=="강화 가죽갑옷") index=i;
 Check(index>=0,"강화 가죽갑옷 missing"); item=items[2].GetValue(index);
 Check(Int(item,"price")==45 && Int(item,"unlockGuildLevel")==3 && Int(item,"productionCost")==1 && Int(item,"hpRecovery")==0 && Int(item,"attackBonus")==0 && Int(item,"defenseBonus")==4 && (string)Get(item,"allowedJob")=="전사·궁수","강화 가죽갑옷 values");
 offset=index; for(int c=0;c<2;c++) offset+=items[c].Length;
 Check(string.Join(",",recipes[offset])=="0,0,0,0,2,4,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0","강화 가죽갑옷 recipe");
 index=-1; for(int i=0;i<items[2].Length;i++) if((string)Get(items[2].GetValue(i),"name")=="수호자의 방패") index=i;
 Check(index>=0,"수호자의 방패 missing"); item=items[2].GetValue(index);
 Check(Int(item,"price")==52 && Int(item,"unlockGuildLevel")==4 && Int(item,"productionCost")==1 && Int(item,"hpRecovery")==0 && Int(item,"attackBonus")==0 && Int(item,"defenseBonus")==5 && (string)Get(item,"allowedJob")=="전사","수호자의 방패 values");
 offset=index; for(int c=0;c<2;c++) offset+=items[c].Length;
 Check(string.Join(",",recipes[offset])=="0,0,0,3,3,0,0,0,0,1,0,0,0,0,0,0,0,3,0,0,0,0,0,0","수호자의 방패 recipe");
 index=-1; for(int i=0;i<items[2].Length;i++) if((string)Get(items[2].GetValue(i),"name")=="마법 망토") index=i;
 Check(index>=0,"마법 망토 missing"); item=items[2].GetValue(index);
 Check(Int(item,"price")==48 && Int(item,"unlockGuildLevel")==7 && Int(item,"productionCost")==1 && Int(item,"hpRecovery")==0 && Int(item,"attackBonus")==0 && Int(item,"defenseBonus")==3 && (string)Get(item,"allowedJob")=="마법사","마법 망토 values");
 offset=index; for(int c=0;c<2;c++) offset+=items[c].Length;
 Check(string.Join(",",recipes[offset])=="0,0,0,0,0,3,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0","마법 망토 recipe");
 index=-1; for(int i=0;i<items[2].Length;i++) if((string)Get(items[2].GetValue(i),"name")=="은강철 갑옷") index=i;
 Check(index>=0,"은강철 갑옷 missing"); item=items[2].GetValue(index);
 Check(Int(item,"price")==110 && Int(item,"unlockGuildLevel")==8 && Int(item,"productionCost")==2 && Int(item,"hpRecovery")==0 && Int(item,"attackBonus")==0 && Int(item,"defenseBonus")==7 && (string)Get(item,"allowedJob")=="전사","용비늘 갑옷 values");
 offset=index; for(int c=0;c<2;c++) offset+=items[c].Length;
 Check(string.Join(",",recipes[offset])=="0,0,0,0,4,3,0,0,0,0,0,0,0,0,2,3,0,0,0,0,0,0,1,0","은강철 갑옷 recipe");
 index=-1; for(int i=0;i<items[2].Length;i++) if((string)Get(items[2].GetValue(i),"name")=="왕실 수호 방패") index=i;
 Check(index>=0,"왕실 수호 방패 missing"); item=items[2].GetValue(index);
 Check(Int(item,"price")==125 && Int(item,"unlockGuildLevel")==8 && Int(item,"productionCost")==2 && Int(item,"hpRecovery")==0 && Int(item,"attackBonus")==0 && Int(item,"defenseBonus")==8 && (string)Get(item,"allowedJob")=="전사","왕실 수호 방패 values");
 offset=index; for(int c=0;c<2;c++) offset+=items[c].Length;
 Check(string.Join(",",recipes[offset])=="0,0,0,0,4,0,0,0,0,2,0,0,0,0,0,3,0,4,0,0,1,0,0,0","왕실 수호 방패 recipe");
 index=-1; for(int i=0;i<items[2].Length;i++) if((string)Get(items[2].GetValue(i),"name")=="별빛 로브") index=i;
 Check(index>=0,"별빛 로브 missing"); item=items[2].GetValue(index);
 Check(Int(item,"price")==118 && Int(item,"unlockGuildLevel")==9 && Int(item,"productionCost")==2 && Int(item,"hpRecovery")==0 && Int(item,"attackBonus")==0 && Int(item,"defenseBonus")==6 && (string)Get(item,"allowedJob")=="마법사","별빛 로브 values");
 offset=index; for(int c=0;c<2;c++) offset+=items[c].Length;
 Check(string.Join(",",recipes[offset])=="0,0,0,0,0,4,0,0,2,0,0,0,0,0,0,0,2,0,0,0,0,0,0,1","별빛 로브 recipe");
 Check(((int[])Get(game,"materialUnlockLevels"))[0]==1 && ((int[])Get(game,"materialMinYield"))[0]==2 && ((int[])Get(game,"materialMaxYield"))[0]==3,"Material 0");
 Check(((int[])Get(game,"materialUnlockLevels"))[1]==1 && ((int[])Get(game,"materialMinYield"))[1]==2 && ((int[])Get(game,"materialMaxYield"))[1]==3,"Material 1");
 Check(((int[])Get(game,"materialUnlockLevels"))[2]==1 && ((int[])Get(game,"materialMinYield"))[2]==1 && ((int[])Get(game,"materialMaxYield"))[2]==2,"Material 2");
 Check(((int[])Get(game,"materialUnlockLevels"))[3]==1 && ((int[])Get(game,"materialMinYield"))[3]==2 && ((int[])Get(game,"materialMaxYield"))[3]==3,"Material 3");
 Check(((int[])Get(game,"materialUnlockLevels"))[4]==1 && ((int[])Get(game,"materialMinYield"))[4]==1 && ((int[])Get(game,"materialMaxYield"))[4]==2,"Material 4");
 Check(((int[])Get(game,"materialUnlockLevels"))[5]==1 && ((int[])Get(game,"materialMinYield"))[5]==1 && ((int[])Get(game,"materialMaxYield"))[5]==2,"Material 5");
 Check(((int[])Get(game,"materialUnlockLevels"))[6]==2 && ((int[])Get(game,"materialMinYield"))[6]==1 && ((int[])Get(game,"materialMaxYield"))[6]==2,"Material 6");
 Check(((int[])Get(game,"materialUnlockLevels"))[7]==3 && ((int[])Get(game,"materialMinYield"))[7]==1 && ((int[])Get(game,"materialMaxYield"))[7]==2,"Material 7");
 Check(((int[])Get(game,"materialUnlockLevels"))[8]==7 && ((int[])Get(game,"materialMinYield"))[8]==1 && ((int[])Get(game,"materialMaxYield"))[8]==2,"Material 8");
 Check(((int[])Get(game,"materialUnlockLevels"))[9]==4 && ((int[])Get(game,"materialMinYield"))[9]==1 && ((int[])Get(game,"materialMaxYield"))[9]==2,"Material 9");
 Check(((int[])Get(game,"materialUnlockLevels"))[10]==2 && ((int[])Get(game,"materialMinYield"))[10]==2 && ((int[])Get(game,"materialMaxYield"))[10]==3,"Material 10");
 Check(((int[])Get(game,"materialUnlockLevels"))[11]==3 && ((int[])Get(game,"materialMinYield"))[11]==1 && ((int[])Get(game,"materialMaxYield"))[11]==2,"Material 11");
 Check(((int[])Get(game,"materialUnlockLevels"))[12]==4 && ((int[])Get(game,"materialMinYield"))[12]==1 && ((int[])Get(game,"materialMaxYield"))[12]==2,"Material 12");
 Check(((int[])Get(game,"materialUnlockLevels"))[13]==2 && ((int[])Get(game,"materialMinYield"))[13]==1 && ((int[])Get(game,"materialMaxYield"))[13]==2,"Material 13");
 Check(((int[])Get(game,"materialUnlockLevels"))[14]==3 && ((int[])Get(game,"materialMinYield"))[14]==1 && ((int[])Get(game,"materialMaxYield"))[14]==2,"Material 14");
 Check(((int[])Get(game,"materialUnlockLevels"))[15]==6 && ((int[])Get(game,"materialMinYield"))[15]==1 && ((int[])Get(game,"materialMaxYield"))[15]==2,"Material 15");
 Check(((int[])Get(game,"materialUnlockLevels"))[16]==7 && ((int[])Get(game,"materialMinYield"))[16]==1 && ((int[])Get(game,"materialMaxYield"))[16]==2,"Material 16");
 Check(((int[])Get(game,"materialUnlockLevels"))[17]==1 && ((int[])Get(game,"materialMinYield"))[17]==2 && ((int[])Get(game,"materialMaxYield"))[17]==3,"Material 17");
 Check(((int[])Get(game,"materialUnlockLevels"))[18]==6 && ((int[])Get(game,"materialMinYield"))[18]==0 && ((int[])Get(game,"materialMaxYield"))[18]==0,"Material 18");
 Check(((int[])Get(game,"materialUnlockLevels"))[19]==8 && ((int[])Get(game,"materialMinYield"))[19]==0 && ((int[])Get(game,"materialMaxYield"))[19]==0,"Material 19");
 Check(((int[])Get(game,"materialUnlockLevels"))[20]==7 && ((int[])Get(game,"materialMinYield"))[20]==0 && ((int[])Get(game,"materialMaxYield"))[20]==0,"Material 20");
 Check(((int[])Get(game,"materialUnlockLevels"))[21]==7 && ((int[])Get(game,"materialMinYield"))[21]==0 && ((int[])Get(game,"materialMaxYield"))[21]==0,"Material 21");
 Check(((int[])Get(game,"materialUnlockLevels"))[22]==8 && ((int[])Get(game,"materialMinYield"))[22]==0 && ((int[])Get(game,"materialMaxYield"))[22]==0,"Material 22");
 Check(((int[])Get(game,"materialUnlockLevels"))[23]==9 && ((int[])Get(game,"materialMinYield"))[23]==0 && ((int[])Get(game,"materialMaxYield"))[23]==0,"Material 23");
  Set(game,"guildLevel",1); Check((int)Call(game,"GuildExperienceRequired",1)==60 && (int)Call(game,"DailyQuestBoardCount",1)==3 && (int)Call(game,"DailyActionCapacity")==2,"Guild level 1");
  IList visitors=(IList)Get(game,"guests");
  Check(visitors.Count==6,"Authored visitor pool");
  foreach(object visitor in visitors) Check(Int(visitor,"level")==1,"All authored visitors start at level 1");
  Set(game,"guildLevel",2); Check((int)Call(game,"GuildExperienceRequired",2)==100 && (int)Call(game,"DailyQuestBoardCount",2)==4 && (int)Call(game,"DailyActionCapacity")==2,"Guild level 2");
  Set(game,"guildLevel",3); Check((int)Call(game,"GuildExperienceRequired",3)==150 && (int)Call(game,"DailyQuestBoardCount",3)==4 && (int)Call(game,"DailyActionCapacity")==3,"Guild level 3");
  Set(game,"guildLevel",4); Check((int)Call(game,"GuildExperienceRequired",4)==220 && (int)Call(game,"DailyQuestBoardCount",4)==5 && (int)Call(game,"DailyActionCapacity")==3,"Guild level 4");
  Set(game,"guildLevel",5); Check((int)Call(game,"GuildExperienceRequired",5)==300 && (int)Call(game,"DailyQuestBoardCount",5)==5 && (int)Call(game,"DailyActionCapacity")==4,"Guild level 5");
  Set(game,"guildLevel",6); Check((int)Call(game,"GuildExperienceRequired",6)==400 && (int)Call(game,"DailyQuestBoardCount",6)==6 && (int)Call(game,"DailyActionCapacity")==4,"Guild level 6");
  Set(game,"guildLevel",7); Check((int)Call(game,"GuildExperienceRequired",7)==520 && (int)Call(game,"DailyQuestBoardCount",7)==6 && (int)Call(game,"DailyActionCapacity")==5,"Guild level 7");
  Set(game,"guildLevel",8); Check((int)Call(game,"GuildExperienceRequired",8)==660 && (int)Call(game,"DailyQuestBoardCount",8)==6 && (int)Call(game,"DailyActionCapacity")==5,"Guild level 8");
  Set(game,"guildLevel",9); Check((int)Call(game,"GuildExperienceRequired",9)==820 && (int)Call(game,"DailyQuestBoardCount",9)==6 && (int)Call(game,"DailyActionCapacity")==6,"Guild level 9");
  Set(game,"guildLevel",10); Check((int)Call(game,"GuildExperienceRequired",10)==0 && (int)Call(game,"DailyQuestBoardCount",10)==6 && (int)Call(game,"DailyActionCapacity")==6,"Guild level 10");
 Check(((int[][])Get(game,"facilityCosts"))[0][0]==100,"Facility price");
 Check(((int[][])Get(game,"facilityCosts"))[0][1]==200,"Facility price");
 Check(((int[][])Get(game,"facilityCosts"))[0][2]==350,"Facility price");
 Check(((int[][])Get(game,"facilityCosts"))[0][3]==550,"Facility price");
 Check(((int[][])Get(game,"facilityCosts"))[0].Length==4,"Guild expansion has four upgrades for six seats");
 Check(((int[][])Get(game,"facilityCosts"))[1][0]==80,"Facility price");
 Check(((int[][])Get(game,"facilityCosts"))[1][1]==150,"Facility price");
 Check(((int[][])Get(game,"facilityCosts"))[1][2]==260,"Facility price");
 Check(((int[][])Get(game,"facilityCosts"))[1][3]==420,"Facility price");
 Check(((int[][])Get(game,"facilityCosts"))[1][4]==650,"Facility price");
 Check(((int[][])Get(game,"facilityCosts"))[2][0]==100,"Facility price");
 Check(((int[][])Get(game,"facilityCosts"))[2][1]==220,"Facility price");
 Check(((int[][])Get(game,"facilityCosts"))[2][2]==380,"Facility price");
 Check(((int[][])Get(game,"facilityCosts"))[2][3]==600,"Facility price");
 Check(((int[][])Get(game,"facilityCosts"))[2][4]==900,"Facility price");
 Check(((int[][])Get(game,"facilityCosts"))[3][0]==90,"Facility price");
 Check(((int[][])Get(game,"facilityCosts"))[3][1]==180,"Facility price");
 Check(((int[][])Get(game,"facilityCosts"))[3][2]==320,"Facility price");
 Check(((int[][])Get(game,"facilityCosts"))[3][3]==520,"Facility price");
 Check(((int[][])Get(game,"facilityCosts"))[3][4]==800,"Facility price");
 Check(((int[][])Get(game,"facilityCosts"))[4][0]==120,"Facility price");
 Check(((int[][])Get(game,"facilityCosts"))[4][1]==250,"Facility price");
 Check(((int[][])Get(game,"facilityCosts"))[4][2]==430,"Facility price");
 Check(((int[][])Get(game,"facilityCosts"))[4][3]==680,"Facility price");
 Check(((int[][])Get(game,"facilityCosts"))[4][4]==1000,"Facility price");
 Array catalog=(Array)Get(game,"questCatalog"); object quest;
 quest=catalog.GetValue(0); Check(Int(quest,"unlockGuildLevel")==1 && Int(quest,"recommendedLevel")==1 && Int(quest,"reward")==14 && Int(quest,"guildCommission")==2 && Int(quest,"heroExperienceReward")==16 && Int(quest,"guildExperienceReward")==7,"Quest 0");
 quest=catalog.GetValue(1); Check(Int(quest,"unlockGuildLevel")==1 && Int(quest,"recommendedLevel")==2 && Int(quest,"reward")==20 && Int(quest,"guildCommission")==3 && Int(quest,"heroExperienceReward")==22 && Int(quest,"guildExperienceReward")==9,"Quest 1");
 quest=catalog.GetValue(2); Check(Int(quest,"unlockGuildLevel")==1 && Int(quest,"recommendedLevel")==3 && Int(quest,"reward")==26 && Int(quest,"guildCommission")==4 && Int(quest,"heroExperienceReward")==28 && Int(quest,"guildExperienceReward")==11,"Quest 2");
 quest=catalog.GetValue(3); Check(Int(quest,"unlockGuildLevel")==2 && Int(quest,"recommendedLevel")==4 && Int(quest,"reward")==32 && Int(quest,"guildCommission")==5 && Int(quest,"heroExperienceReward")==34 && Int(quest,"guildExperienceReward")==13,"Quest 3");
 quest=catalog.GetValue(4); Check(Int(quest,"unlockGuildLevel")==2 && Int(quest,"recommendedLevel")==5 && Int(quest,"reward")==38 && Int(quest,"guildCommission")==6 && Int(quest,"heroExperienceReward")==40 && Int(quest,"guildExperienceReward")==15,"Quest 4");
 quest=catalog.GetValue(5); Check(Int(quest,"unlockGuildLevel")==3 && Int(quest,"recommendedLevel")==6 && Int(quest,"reward")==44 && Int(quest,"guildCommission")==7 && Int(quest,"heroExperienceReward")==46 && Int(quest,"guildExperienceReward")==17,"Quest 5");
 quest=catalog.GetValue(6); Check(Int(quest,"unlockGuildLevel")==3 && Int(quest,"recommendedLevel")==7 && Int(quest,"reward")==50 && Int(quest,"guildCommission")==8 && Int(quest,"heroExperienceReward")==52 && Int(quest,"guildExperienceReward")==19,"Quest 6");
 quest=catalog.GetValue(7); Check(Int(quest,"unlockGuildLevel")==4 && Int(quest,"recommendedLevel")==8 && Int(quest,"reward")==56 && Int(quest,"guildCommission")==8 && Int(quest,"heroExperienceReward")==58 && Int(quest,"guildExperienceReward")==21,"Quest 7");
 quest=catalog.GetValue(8); Check(Int(quest,"unlockGuildLevel")==4 && Int(quest,"recommendedLevel")==9 && Int(quest,"reward")==62 && Int(quest,"guildCommission")==9 && Int(quest,"heroExperienceReward")==64 && Int(quest,"guildExperienceReward")==23,"Quest 8");
 quest=catalog.GetValue(9); Check(Int(quest,"unlockGuildLevel")==5 && Int(quest,"recommendedLevel")==10 && Int(quest,"reward")==68 && Int(quest,"guildCommission")==10 && Int(quest,"heroExperienceReward")==70 && Int(quest,"guildExperienceReward")==25,"Quest 9");
 quest=catalog.GetValue(10); Check(Int(quest,"unlockGuildLevel")==6 && Int(quest,"recommendedLevel")==12 && Int(quest,"reward")==80 && Int(quest,"guildCommission")==12 && Int(quest,"heroExperienceReward")==82 && Int(quest,"guildExperienceReward")==29,"Quest 10");
 quest=catalog.GetValue(11); Check(Int(quest,"unlockGuildLevel")==7 && Int(quest,"recommendedLevel")==14 && Int(quest,"reward")==92 && Int(quest,"guildCommission")==14 && Int(quest,"heroExperienceReward")==94 && Int(quest,"guildExperienceReward")==33,"Quest 11");
 quest=catalog.GetValue(12); Check(Int(quest,"unlockGuildLevel")==8 && Int(quest,"recommendedLevel")==16 && Int(quest,"reward")==104 && Int(quest,"guildCommission")==16 && Int(quest,"heroExperienceReward")==106 && Int(quest,"guildExperienceReward")==37,"Quest 12");
 quest=catalog.GetValue(13); Check(Int(quest,"unlockGuildLevel")==9 && Int(quest,"recommendedLevel")==18 && Int(quest,"reward")==116 && Int(quest,"guildCommission")==17 && Int(quest,"heroExperienceReward")==118 && Int(quest,"guildExperienceReward")==41,"Quest 13");
 quest=catalog.GetValue(14); Check(Int(quest,"unlockGuildLevel")==10 && Int(quest,"recommendedLevel")==20 && Int(quest,"reward")==128 && Int(quest,"guildCommission")==19 && Int(quest,"heroExperienceReward")==130 && Int(quest,"guildExperienceReward")==45,"Quest 14");
 Done(game,"Workbook parity: 80 class/level rows, XP curves, 27 products/recipes, 24 materials, 10 guild levels, 25 upgrade costs, 15 quests.");
 }
}
